// <auto-generated />
using System;
using AuditLoggerPoc.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditLoggerPoc.Migrations
{
    [DbContext(typeof(UserDatabaseContext))]
    [Migration("20230412070701_Added-Audit-Trail-table")]
    partial class AddedAuditTrailtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("AuditLoggerPoc.AuditTrailData", b =>
                {
                    b.Property<Guid>("TrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("affectedColumns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("newValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("oldValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("primaryKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TrailId");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("AuditLoggerPoc.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
